/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 8.1.0   2018-05-19

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include <scmRTOS.h>

/* Private macro */
typedef OS::process<OS::pr0, 300> TProc0;
typedef OS::process<OS::pr1, 300> TProc1;

uint32_t i = 0;
OS::TEventFlag _ev;
OS::TEventFlag _ev1;


//---------------------------------------------------------------------------
//
//      Process objects
//
TProc0 Proc0;
TProc1 Proc1;
/* Private variables */
//GPIO_InitTypeDef  GPIO_InitStructure;
//TIM_TimeBaseInitTypeDef TIM2_init;
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;//RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;// RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);


	  GPIOA->MODER |= GPIO_MODER_MODER5_0; //GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT; GPIO_InitStructure.GPIO_Pin = GPIO_Pin_5;
	  GPIOA->OTYPER &= ~ GPIO_OTYPER_OT_5;//GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	  GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_0; //GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
	  //GPIOA->PUPDR |= GPIO_PUPDR_PUPDR5_0;//GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
	  //GPIO_Init(GPIOA, &GPIO_InitStructure);
	  GPIOA->BSRRL |= GPIO_Pin_5;//GPIO_SetBits(GPIOA, GPIO_Pin_5);



	  TIM2->PSC = 42000 - 1; // Настраиваем делитель что таймер тикал 1000 раз в секунду
	  TIM2->ARR = 1000 - 1; // Чтоб прерывание случалось раз в секунду
	  TIM2->DIER |= TIM_DIER_UIE; //разрешаем прерывание от таймера
	  TIM2->CR1 |= TIM_CR1_CEN; // Начать отсчёт!
	  NVIC_EnableIRQ(TIM2_IRQn);
	  /*TIM_TimeBaseStructInit(&TIM2_init);
	  TIM2_init.TIM_Prescaler = 42000 - 1; // частота счета 10 КГц
	  //TIM2_init.TIM_CounterMode = TIM_CounterMode_Up;
	  TIM2_init.TIM_Period = 1000 - 1;
	  //TIM2->DIER|=TIM_DIER_UIE;
	  TIM_TimeBaseInit(TIM2, &TIM2_init);
	  TIM2->DIER |= TIM_IT_Update;//TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);
	  TIM2->CR1 |= TIM_CR1_CEN;//TIM_Cmd(TIM2, ENABLE);
	  NVIC_EnableIRQ(TIM2_IRQn);*/

	  OS::run();

}

namespace OS
{
    template <>
    OS_PROCESS void TProc0::exec()
    {
        for(;;)
        {	//sleep(1000);
        	_ev.wait();
        	GPIOA->BSRRH |= GPIO_Pin_5;//GPIO_ResetBits(GPIOA, GPIO_Pin_5);
        	//sleep();
        	//sleep(1000);
        }
    }
    template <>
    OS_PROCESS void TProc1::exec()
        {
            for(;;)
            {
            	//sleep(1000);
            	_ev1.wait();
            	GPIOA->BSRRL |= GPIO_Pin_5;//GPIO_SetBits(GPIOA, GPIO_Pin_5);
            	//sleep(1000);
            }
        }



}

OS_INTERRUPT extern "C" void TIM2_IRQHandler(){
	OS::TISRW_SS TISRW_O;
	i++;
	//TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
	if (i%2 == 0){
		_ev.signal_isr();}
	else{
		_ev1.signal_isr();}
	TIM2->SR &= ~TIM_SR_UIF;//(uint16_t)~TIM_FLAG_Update;//TIM_ClearFlag(TIM2, TIM_FLAG_Update);
	//TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
}



#if scmRTOS_IDLE_HOOK_ENABLE
void OS::idle_process_user_hook()
{
	__WFI();
}
#endif
